# Numpy library

First we need to (if we have not done it already) install the library. While on a jupyter notebook one easy way to do it is type this command:

In [ ]:
!pip install numpy

In [2]:
import numpy as np

## Array Creation

The easiest way to create a Numpy array is using the method array()

In [3]:
a = np.array([1, 2, 3])

In a Jupyter notebook environment you can print the contents of a variable by just typing the name of the variable in a cell and running it.

In [4]:
a

array([1, 2, 3])

You can also create a multidimensional array:

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

You can create arrays filled with zeros or ones:

In [7]:
np.zeros((2, 3)) # 2 rows, 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 3)) # 2 rows, 3 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

There is also the possibility of create an array with random values (depends on the state of the memory).

In [10]:
np.empty((3, 5)) # 3 rows, 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [13]:
np.arange(1, 22, 4) # start, stop, step

array([ 1,  5,  9, 13, 17, 21])

## Basic Operations

Get the shape of an array:

In [14]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])

my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
my_array.shape  # 2 rows, 3 columns

(2, 3)

Reshape an array:

In [17]:
my_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = my_array.reshape(2, 3)
print(reshaped_array) # 2 rows, 3 columns

[[1 2 3]
 [4 5 6]]


Perform mathematical operations on arrays:

In [18]:
my_array = np.array([1, 2, 3, 4, 5])
my_array = my_array * 2  # multiply each element by 2
print(my_array) 

[ 2  4  6  8 10]


Perform statistical operations:

In [19]:
# Get the mean of the array

my_array = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(my_array)
print(mean_value) # Output: 3.0

3.0


In [20]:
# Get the median of the array

median_value = np.median(my_array)
print(median_value) # Output: 3.0

3.0


Perform linear algebra operations:

In [21]:
# Matrix multiplication

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.dot(a, b)  # matrix multiplication

print(c)

[[19 22]
 [43 50]]


In [38]:
# Get the transpose of a matrix

t = np.transpose(multi_array)

multi_array  # the original matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
t  # the transpose of the matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Indexing and slicing

### Indexing

In [23]:
# Get a np.array element by index
my_array = np.array([1, 2, 3, 4, 5])

my_array[0] # first element

1

In [24]:
my_array[2] # third element

3

In [26]:
# Getting elements from a multidimensional array

multi_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

multi_array[0, 0] # first row, first column

1

In [27]:
multi_array[1, 2] # second row, third column

6

### Slicing

In [25]:
# get a subarray of elements 1, 2, 3

my_array = np.array([1, 2, 3, 4, 5])
my_array[0:3] # first 3 elements

array([1, 2, 3])

In [29]:
# Slicing in multidimensional arrays

multi_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
multi_array[1:3, 1:3] # second and third rows, second and third columns

array([[5, 6],
       [8, 9]])

## Min, Max, Sum

In [31]:
my_array

array([1, 2, 3, 4, 5])

In [32]:
# Get the maximum value in the array

my_array.max()

5

In [33]:
# Get the minimum value in the array

my_array.min()

1

In [34]:
# Get the sum of the array

my_array.sum()

15

In [35]:
# Get the multiplication of the array

my_array.prod()

120

## Counting and Unique

In [40]:
# Counting non-zero elements

my_array = np.array([1, 0, 2, 0, 3, 4, 0, 5, 0])
count = np.count_nonzero(my_array)
print(count)

5


In [41]:
# Find the unique elements in an array

my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5])
unique_elements = np.unique(my_array)
print(unique_elements) 

[1 2 3 4 5]


In [45]:
# Count the number of times (frequency) each unique element appears in the array

my_array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 7])
(unique_elements, counts) = np.unique(my_array, return_counts=True)

print(unique_elements) 

[1 2 3 4 5 6 7]


In [46]:
print(counts)

[1 2 3 4 5 2 1]
